# -*- coding: utf-8 -*-
"""Face detection using CNN and Dlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/139Bn-Mr7hfkcWu-8wSaMr19QFOd2efLE
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import dlib
from google.colab.patches import cv2_imshow

img = cv2.imread('/content/drive/MyDrive/Histograms of Oriented Gradients (HOG) Algorithm/people1.jpg')

cv2_imshow(img)

CNN_face_detector = dlib.cnn_face_detection_model_v1('/content/drive/MyDrive/mmod_human_face_detector.dat')

CNN_detections = CNN_face_detector(img, 1)

CNN_detections

for faces in CNN_detections:
  left, right, top, bottom, confidence = faces.rect.left(), faces.rect.right(), faces.rect.top(), faces.rect.bottom(), faces.confidence
  print(confidence)
  cv2.rectangle(img, (left, top), (right, bottom), (0,255,255),2)
cv2_imshow(img)

cv2.imwrite('/content/drive/MyDrive/CNN_dlib_face_detection_result.png', img)

def CNN_face_detection(image_path):
  img = cv2.imread(image_path)
  CNN_face_detector = dlib.cnn_face_detection_model_v1('/content/drive/MyDrive/mmod_human_face_detector.dat')
  CNN_detections = CNN_face_detector(img, 1)

  for faces in CNN_detections:
    left, right, top, bottom, confidence = faces.rect.left(), faces.rect.right(), faces.rect.top(), faces.rect.bottom(), faces.confidence
    print(confidence)
  cv2.rectangle(img, (left, top), (right, bottom), (0,255,255),2)
  cv2.imwrite('filename.ext', img) # Insert file name and extension to save
  cv2_imshow(img)

from datetime import datetime
import pytz
datetime.now(pytz.timezone('Europe/Berlin'))